import type { Panel, Service, Order } from './types';

export const panels: Panel[] = [
  {
    id: 'panel-1',
    name: 'SpeedySMM',
    balance: 150.75,
    apiEndpoint: 'https://speedysmm.com/api/v2',
    apiKey: 'key_speedy_123',
  },
  {
    id: 'panel-2',
    name: 'SMMKing',
    balance: 425.5,
    apiEndpoint: 'https://smmking.net/api/v2',
    apiKey: 'key_king_456',
  },
  {
    id: 'panel-3',
    name: 'InstaBoost',
    balance: 89.2,
    apiEndpoint: 'https://instaboost.io/api/v2',
    apiKey: 'key_insta_789',
  },
];

export const services: Service[] = [
  // Instagram Followers
  {
    id: 'svc-001',
    panelId: 'panel-1',
    name: 'Instagram Followers [HQ]',
    category: 'Instagram',
    rate: 1.2,
    min: 100,
    max: 10000,
    estimatedDeliveryTime: '1-2 hours',
  },
  {
    id: 'svc-002',
    panelId: 'panel-2',
    name: 'Instagram Followers [HQ]',
    category: 'Instagram',
    rate: 1.1,
    min: 50,
    max: 20000,
    estimatedDeliveryTime: '3-4 hours',
  },
  {
    id: 'svc-003',
    panelId: 'panel-3',
    name: 'Instagram Followers [Real]',
    category: 'Instagram',
    rate: 2.5,
    min: 100,
    max: 5000,
    estimatedDeliveryTime: '24 hours',
  },
  // Instagram Likes
  {
    id: 'svc-004',
    panelId: 'panel-1',
    name: 'Instagram Likes',
    category: 'Instagram',
    rate: 0.5,
    min: 50,
    max: 5000,
    estimatedDeliveryTime: '30 minutes',
  },
  {
    id: 'svc-005',
    panelId: 'panel-2',
    name: 'Instagram Likes',
    category: 'Instagram',
    rate: 0.45,
    min: 20,
    max: 10000,
    estimatedDeliveryTime: '15 minutes',
  },
  // TikTok Views
  {
    id: 'svc-006',
    panelId: 'panel-2',
    name: 'TikTok Views',
    category: 'TikTok',
    rate: 0.01,
    min: 1000,
    max: 1000000,
    estimatedDeliveryTime: '5 minutes',
  },
  {
    id: 'svc-007',
    panelId: 'panel-1',
    name: 'TikTok Views',
    category: 'TikTok',
    rate: 0.015,
    min: 500,
    max: 500000,
    estimatedDeliveryTime: '10 minutes',
  },
  // YouTube Subscribers
  {
    id: 'svc-008',
    panelId: 'panel-3',
    name: 'YouTube Subscribers',
    category: 'YouTube',
    rate: 15.0,
    min: 10,
    max: 1000,
    estimatedDeliveryTime: '1-3 days',
  },
];

export const orders: Order[] = [
  {
    id: 'ord-1001',
    serviceId: 'svc-005',
    panelId: 'panel-2',
    link: 'https://instagram.com/p/Cxyz...',
    quantity: 1000,
    charge: 0.45,
    date: '2023-10-27T10:00:00Z',
    status: 'Completed',
  },
  {
    id: 'ord-1002',
    serviceId: 'svc-001',
    panelId: 'panel-1',
    link: 'https://instagram.com/username',
    quantity: 500,
    charge: 0.6,
    date: '2023-10-27T11:30:00Z',
    status: 'In Progress',
  },
  {
    id: 'ord-1003',
    serviceId: 'svc-006',
    panelId: 'panel-2',
    link: 'https://tiktok.com/v/abcd...',
    quantity: 50000,
    charge: 0.5,
    date: '2023-10-28T09:00:00Z',
    status: 'Pending',
  },
  {
    id: 'ord-1004',
    serviceId: 'svc-008',
    panelId: 'panel-3',
    link: 'https://youtube.com/channel/UC...',
    quantity: 100,
    charge: 1.5,
    date: '2023-10-26T14:00:00Z',
    status: 'Canceled',
  },
  {
    id: 'ord-1005',
    serviceId: 'svc-002',
    panelId: 'panel-2',
    link: 'https://instagram.com/anotheruser',
    quantity: 2000,
    charge: 2.2,
    date: '2023-10-28T12:15:00Z',
    status: 'Completed',
  },
];
