import type { Panel, Service, Order } from './types';

export const mockPanels: Panel[] = [
  {
    id: 'panel-1',
    name: 'SpeedySMM',
    balance: 150.75,
    apiUrl: 'https://speedysmm.com/api/v2',
    apiKey: 'key_speedy_123',
  },
  {
    id: 'panel-2',
    name: 'SMMKing',
    balance: 425.5,
    apiUrl: 'https://smmking.net/api/v2',
    apiKey: 'key_king_456',
  },
  {
    id: 'panel-3',
    name: 'InstaBoost',
    balance: 89.2,
    apiUrl: 'https://instaboost.io/api/v2',
    apiKey: 'key_insta_789',
  },
];

export const mockServices: Service[] = [
  // Instagram Followers
  {
    id: 'svc-001',
    smmPanelId: 'panel-1',
    name: 'Instagram Followers [HQ]',
    category: 'Instagram',
    rate: 1.2,
    min: 100,
    max: 10000,
    estimatedDeliveryTime: '1-2 hours',
  },
  {
    id: 'svc-002',
    smmPanelId: 'panel-2',
    name: 'Instagram Followers [HQ]',
    category: 'Instagram',
    rate: 1.1,
    min: 50,
    max: 20000,
    estimatedDeliveryTime: '3-4 hours',
  },
  {
    id: 'svc-003',
    smmPanelId: 'panel-3',
    name: 'Instagram Followers [Real]',
    category: 'Instagram',
    rate: 2.5,
    min: 100,
    max: 5000,
    estimatedDeliveryTime: '24 hours',
  },
  // Instagram Likes
  {
    id: 'svc-004',
    smmPanelId: 'panel-1',
    name: 'Instagram Likes',
    category: 'Instagram',
    rate: 0.5,
    min: 50,
    max: 5000,
    estimatedDeliveryTime: '30 minutes',
  },
  {
    id: 'svc-005',
    smmPanelId: 'panel-2',
    name: 'Instagram Likes',
    category: 'Instagram',
    rate: 0.45,
    min: 20,
    max: 10000,
    estimatedDeliveryTime: '15 minutes',
  },
  // TikTok Views
  {
    id: 'svc-006',
    smmPanelId: 'panel-2',
    name: 'TikTok Views',
    category: 'TikTok',
    rate: 0.01,
    min: 1000,
    max: 1000000,
    estimatedDeliveryTime: '5 minutes',
  },
  {
    id: 'svc-007',
    smmPanelId: 'panel-1',
    name: 'TikTok Views',
    category: 'TikTok',
    rate: 0.015,
    min: 500,
    max: 500000,
    estimatedDeliveryTime: '10 minutes',
  },
  // YouTube Subscribers
  {
    id: 'svc-008',
    smmPanelId: 'panel-3',
    name: 'YouTube Subscribers',
    category: 'YouTube',
    rate: 15.0,
    min: 10,
    max: 1000,
    estimatedDeliveryTime: '1-3 days',
  },
];


export const mockOrders: Order[] = [
    {
      id: "order-001",
      serviceId: "svc-001",
      link: "https://instagram.com/user1",
      quantity: 1000,
      charge: 1.20,
      createdAt: "2023-10-26T10:00:00Z",
      status: "Completed",
      panelId: "panel-1",
      userId: "local-user-123",
      antiCheatStatus: 'SAFE',
      flagged: false,
    },
    {
      id: "order-002",
      serviceId: "svc-004",
      link: "https://instagram.com/p/post-id",
      quantity: 500,
      charge: 0.25,
      createdAt: "2023-10-27T11:30:00Z",
      status: "In Progress",
      panelId: "panel-1",
      userId: "local-user-123",
      antiCheatStatus: 'MONITORING',
      flagged: false,
    },
    {
      id: "order-003",
      serviceId: "svc-006",
      link: "https://tiktok.com/@user/video/123",
      quantity: 10000,
      charge: 1.00,
      createdAt: "2023-10-28T14:00:00Z",
      status: "Pending",
      panelId: "panel-2",
      userId: "local-user-123",
      antiCheatStatus: 'SAFE',
      flagged: false,
    },
    {
      id: "order-004",
      serviceId: "svc-008",
      link: "https://youtube.com/channel/user-channel",
      quantity: 100,
      charge: 15.00,
      createdAt: "2023-10-28T18:00:00Z",
      status: "Completed",
      panelId: "panel-3",
      userId: "local-user-123",
      antiCheatStatus: 'SAFE',
      flagged: false,
    },
    {
      id: "order-005",
      serviceId: "svc-002",
      link: "https://instagram.com/user2",
      quantity: 2000,
      charge: 2.20,
      createdAt: "2023-10-29T09:00:00Z",
      status: "Canceled",
      panelId: "panel-2",
      userId: "local-user-123",
      antiCheatStatus: 'DETECTED',
      flagged: true,
    }
  ];
